#!/usr/bin/env node
/**
 * Bundle packages/github/src/action.ts into dist/action.js
 * Resolves workspace package imports to their source .ts files.
 */

import { build } from 'esbuild';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(__dirname, '..');

/** Map workspace package subpath imports to source .ts files */
const workspaceResolverPlugin = {
  name: 'workspace-resolver',
  setup(build) {
    build.onResolve({ filter: /^@codeagora\/(core|shared|github)/ }, (args) => {
      const match = args.path.match(/^@codeagora\/(core|shared|github)\/(.+?)(?:\.js)?$/);
      if (!match) return null;
      const [, pkg, subpath] = match;
      const tsPath = path.resolve(root, 'packages', pkg, 'src', subpath + '.ts');
      return { path: tsPath };
    });
  },
};

/** Shim native optional deps that are never used at runtime */
const nativeShimPlugin = {
  name: 'native-shim',
  setup(build) {
    build.onResolve({ filter: /^@basetenlabs\// }, () => ({
      path: 'basetenlabs-shim',
      namespace: 'shim',
    }));
    build.onLoad({ filter: /.*/, namespace: 'shim' }, () => ({
      contents: 'export default {}; export class PerformanceClient { constructor() {} mark() {} measure() {} }',
      loader: 'js',
    }));
  },
};

try {
  const result = await build({
    entryPoints: [path.resolve(root, 'packages/github/src/action.ts')],
    bundle: true,
    platform: 'node',
    target: 'node20',
    format: 'esm',
    outfile: path.resolve(root, 'dist/action.js'),
    plugins: [workspaceResolverPlugin, nativeShimPlugin],
    external: [],
    loader: { '.node': 'empty' },
    banner: {
      js: '// Auto-generated by scripts/build-action.mjs — do not edit\nimport { createRequire } from "module"; const require = createRequire(import.meta.url);',
    },
    sourcemap: false,
    minify: false,
    treeShaking: true,
  });
  console.log(`✓ dist/action.js built (${result.errors.length} errors, ${result.warnings.length} warnings)`);
} catch (e) {
  console.error('Build failed:', e.message);
  process.exit(1);
}
